### ISSUE TITLE
FTPS trouble

### ISSUE THREAD

**Issue by OMRKiruha** [deniskovalchuk/libftp#19]
I'm used examples code to connect to server via SSH/FTPS, but response was wrong. 

```
        ftp::ssl::context_ptr ssl_context = ftp::ssl::create_context(ftp::ssl::context::tlsv13_client, true);
        ssl_context->set_default_verify_paths();
        ssl_context->set_verify_mode(ftp::ssl::verify_peer);

        ftp::client client(std::move(ssl_context));
        handle_reply(client.connect(hostname, 22, "user",  "pass"));
```

```
terminate called after throwing an instance of 'ftp::ftp_exception'
  what():  Cannot parse a status code from the server reply: 'SSH-2.0-dropbear_2022.82'.
```

Please tell what the problem might be. It is possible that when connecting via SSH/FTPS, the order of operations differs from the usual FTPS on port 21. Maybe need to apply some unusual settings on server??

**Comment by deniskovalchuk** [comment]
Hi!

`libftp` doesn't support [SFTP (SSH FTP)](https://filezilla-project.org/specs/draft-ietf-secsh-filexfer-02.txt), only [FTP](https://datatracker.ietf.org/doc/html/rfc959) and [FTPS](https://datatracker.ietf.org/doc/html/rfc4217).

AFAIK there is a confusion in terminology. SFTP is an extension of SSH and has nothing to do with FTP/FTPS.
