### ISSUE TITLE
In-memory download

### ISSUE THREAD

**Issue by rbrugo** [deniskovalchuk/libftp#20]
Hi, and thank you for the lib!
I'd like to download a file in-memory, for example in a `std::string` or in a `std::vector<std::byte>` instead of saving it on the disk, but I can't find a way from the examples.
Is it currently possible?

**Comment by deniskovalchuk** [comment]
Hi!

`libftp` provides

1. [`ftp::output_stream`](https://github.com/deniskovalchuk/libftp/blob/ad0c10dabd5dd29c027d9639ed76771dd4bf770f/include/ftp/stream/output_stream.hpp#L35) interface for downloading data.
2. [`ftp::input_stream`](https://github.com/deniskovalchuk/libftp/blob/ad0c10dabd5dd29c027d9639ed76771dd4bf770f/include/ftp/stream/input_stream.hpp#L35) interface for uploading data.

These interfaces can be implemented based on any container.

For example, there are

1. [`ftp::ostream_adapter`](https://github.com/deniskovalchuk/libftp/blob/ad0c10dabd5dd29c027d9639ed76771dd4bf770f/include/ftp/stream/ostream_adapter.hpp#L35) class that implements the `ftp::output_stream` for working with a `std::ostream`.
2. [`ftp::istream_adapter`](https://github.com/deniskovalchuk/libftp/blob/ad0c10dabd5dd29c027d9639ed76771dd4bf770f/include/ftp/stream/istream_adapter.hpp#L35) class that implements the `ftp::input_stream` for working with a `std::istream`.

Based on this:

1. To download a file into a `std::string` you can use the `ftp::ostream_adapter` with a `std::ostringstream`:

```cpp
#include <string>
#include <sstream>
#include <ftp/client.hpp>
#include <ftp/stream/ostream_adapter.hpp>

int main()
{
    ftp::client client;

    ...

    std::ostringstream oss;

    client.download_file(ftp::ostream_adapter(oss), "path/to/file");

    std::string content = oss.str();

    ...

    return 0;
}
```

2. To download a file into a `std::vector<std::byte>` you need to implement the `ftp::output_stream` appropriately:

```cpp
#include <vector>
#include <ftp/client.hpp>
#include <ftp/stream/ostream_adapter.hpp>

class vector_output_stream : public ftp::output_stream
{
public:
    vector_output_stream(std::vector<std::byte> & content)
        : content_(content)
    {}

    void write(char *buf, std::size_t size) override
    {
        const std::byte *bytes = reinterpret_cast<const std::byte *>(buf);
        content_.insert(content_.end(), bytes, bytes + size);
    }

    void flush() override
    {
        // Do nothing.
    }

private:
    std::vector<std::byte> & content_;
};

int main()
{
    ftp::client client;

    ...

    std::vector<std::byte> content;

    // Pre-allocate memory for 'content' if desired.

    client.download_file(vector_output_stream(content), "path/to/file");

    ...

    return 0;
}
```

Hope this helps!

**Comment by rbrugo** [comment]
This helps indeed. Thank you so much!
