### ISSUE TITLE
support boost1.87.0

### ISSUE THREAD

**Issue by miyanyan** [deniskovalchuk/libftp#21]
hi, asio removed some previously deprecated facilities, see https://www.boost.org/doc/libs/1_87_0/doc/html/boost_asio/history.html, I found some build errors when I want to update boost for vcpkg

**Comment by deniskovalchuk** [comment]
@miyanyan, thanks!

I've released [v1.4.1](https://github.com/deniskovalchuk/libftp/releases/tag/v1.4.1) with a fix and updated the [vcpkg port](https://github.com/microsoft/vcpkg/pull/42852).
